# Generated by Django 5.0.7 on 2024-07-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HouseholdTasks',
            new_name='HouseholdTask',
        ),
        migrations.RenameModel(
            old_name='OfficeTasks',
            new_name='OfficeTask',
        ),
        migrations.RenameModel(
            old_name='SideskillsTasks',
            new_name='SideskillsTask',
        ),
        migrations.RenameModel(
            old_name='WorkoutTasks',
            new_name='WorkoutTask',
        ),
    ]
