# Generated by Django 5.0.7 on 2024-07-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_householdtasks_householdtask_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workouttask',
            old_name='locatioin',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='officetask',
            name='status',
        ),
        migrations.RemoveField(
            model_name='workouttask',
            name='intensity',
        ),
        migrations.AddField(
            model_name='householdtask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officetask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sideskillstask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workouttask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
