# Generated by Django 5.0.7 on 2024-07-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_locatioin_workouttask_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdtask',
            name='assignee',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='householdtask',
            name='equipment',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='householdtask',
            name='notes',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='householdtask',
            name='priority',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='householdtask',
            name='room',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='officetask',
            name='notes',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='sideskillstask',
            name='goal',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sideskillstask',
            name='notes',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='sideskillstask',
            name='resources',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sideskillstask',
            name='skillcategory',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workouttask',
            name='duration',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='workouttask',
            name='equipment',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='workouttask',
            name='goal',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workouttask',
            name='notes',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='workouttask',
            name='type',
            field=models.CharField(max_length=80),
        ),
    ]
