# Generated by Django 5.0.7 on 2024-07-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_householdtask_assignee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officetask',
            name='duedate',
            field=models.DateField(max_length=30),
        ),
        migrations.AlterField(
            model_name='officetask',
            name='estimatedtime',
            field=models.TimeField(max_length=50),
        ),
    ]
