# Generated by Django 5.0.7 on 2024-07-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_officetask_duedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officetask',
            name='duedate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='officetask',
            name='estimatedtime',
            field=models.TimeField(),
        ),
    ]
